app/forms/data_analysis.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField, IntegerField, RadioField, SelectMultipleField
from wtforms.widgets import CheckboxInput, Select
from wtforms.validators import DataRequired


class DataAnalysisForm(FlaskForm):

    # 选择不处理异常值的列
    exclude_column = SelectMultipleField('不处理异常值的列',
                                         choices=[],
                                         option_widget=CheckboxInput())

    # 选择缺失值填充方法
    fillna_method = SelectField('缺失值填充方法', choices=[
        ('ffill', '向前填充'),
        ('bfill', '向后填充'),
        ('mean', '均值填充'),
        ('median', '中位数填充')
    ])
    # 选择不必要的列
    unneccessary_column = SelectMultipleField('不需要的列',
                                              choices=[],
                                              option_widget=CheckboxInput())

    submit = SubmitField('提交')

app/forms/login.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo

class LoginForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired()])
    password = PasswordField('密码', validators=[DataRequired()])
    submit = SubmitField('登录')

app/forms/plot.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField, IntegerField, RadioField, SelectMultipleField
from wtforms.fields.simple import BooleanField
from wtforms.widgets import CheckboxInput, ListWidget   # 复选框，不用按键就能多选
from wtforms.validators import DataRequired, Optional, NumberRange


# class PlotForm(FlaskForm):
#     # select下拉框
#     x_column = SelectField('X轴', choices=[], validators=[DataRequired()])
#     y_column = SelectField('Y轴', choices=[], validators=[DataRequired()])
#     num_rows = IntegerField('选择行数', default=10, validators=[DataRequired()])
#     chart_type = SelectField('图表类型', choices=[
#         ('line', '线图'),
#         ('bar', '柱状图'),
#         ('scatter', '散点图'),
#         ('pie', '饼图'),
#         ('histogram', '直方图'),
#         ('box', '箱线图'),
#         ('heatmap', '热图')
#     ])
#     submit = SubmitField('生成图表')

class PlotForm(FlaskForm):
    x_column = SelectField('X轴', choices=[], validators=[DataRequired()])
    y_columns = SelectMultipleField('Y轴', choices=[], validators=[DataRequired()])

    color_column = SelectField('颜色分组', choices=[])
    size_column = SelectField('大小分组', choices=[])
    sort_column = SelectField('排序字段', choices=[], validators=[DataRequired()])
    sort_order = RadioField('排序顺序', choices=[('asc', '升序'), ('desc', '降序')], default='asc')

    num_rows = IntegerField('选择行数', default=10, validators=[DataRequired()])
    chart_type = SelectField('图表类型', choices=[
        ('line', '线图'),
        ('bar', '柱状图'),
        ('scatter', '散点图'),
        ('pie', '饼图'),
        ('histogram', '直方图'),
        ('box', '箱线图'),
        ('heatmap', '热图'),
        ('area', '面积图'),
        ('density', '密度图'),
        ('radar', '雷达图'),
        ('bubble', '气泡图'),
        ('treemap', '树图')
    ])
    exclude_column = SelectMultipleField('不处理异常值的列',
                                         choices=[],
                                         option_widget=CheckboxInput())

    # 选择缺失值填充方法
    fillna_method = SelectField('缺失值填充方法',default='none', choices=[
        ('none', '不填充'),
        ('ffill', '向前填充'),
        ('bfill', '向后填充'),
        ('mean', '均值填充'),
        ('median', '中位数填充')
    ], validators=[DataRequired()])
    # 选择不必要的列
    unneccessary_column = SelectMultipleField('不需要的列',
                                              choices=[],
                                              option_widget=CheckboxInput())

    # 移动平均线
    use_moving_average = BooleanField('启用移动平均')
    moving_average_window = IntegerField('窗口大小', validators=[Optional(), NumberRange(min=1)], default=5)
    submit = SubmitField('生成图表')

app/forms/register.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

class RegisterForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired()])
    email = StringField('邮箱', validators=[DataRequired(), Email()])
    password = PasswordField('密码', validators=[DataRequired()])
    confirm_password = PasswordField('确认密码', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('注册')

app/forms/upload.py
from flask_wtf import FlaskForm
from wtforms import FileField, SubmitField
from wtforms.validators import DataRequired

class UploadForm(FlaskForm):
    file = FileField('选择文件', validators=[DataRequired(), ])
    submit = SubmitField('上传')

app/blueprints/auth.py
from flask import Blueprint, render_template, session, redirect, url_for, flash
from flask_login import current_user, login_required, login_user, logout_user

from app.extensions import db
from app.models import User, File
from app.forms import LoginForm, RegisterForm

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash('登录成功')
            return redirect(url_for('main.index'))
        else:
            flash('用户或密码错误')
            return redirect(url_for('auth.login'))
    return render_template('login.html', form=form)

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            flash('用户名已被注册')
            return redirect(url_for('auth.register'))

        new_user = User(
            username = form.username.data,
            email = form.email.data
        )
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('注册成功')
        return redirect(url_for('auth.login'))
    return render_template('register.html', form=form)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('登出成功')
    return redirect(url_for('main.index'))

@auth_bp.route('/profile')
@login_required
def profile():
    user = User.query.filter_by(username=current_user.username).first()
    uploaded_files = File.query.filter_by(user_id=user.id).all()
    return render_template('profile.html', uploaded_files=uploaded_files)

app/blueprints/file.py
import os

from flask import Blueprint, request, render_template, redirect, url_for, flash
from .utils import save_file, allowed_file, read_file
from .utils_analysis import clean_data, get_cleaned_metrics, get_original_metrics, get_descriptive_stats
from flask_login import current_user, login_required
from app.models import File
from app.extensions import db
from app.forms import UploadForm

file_bp = Blueprint('file', __name__)

@file_bp.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    form = UploadForm() #创建表单实例
    if form.validate_on_submit():   # 验证
        file = form.file.data   # 获取文件对象

        file_path, unique_filename, original_filename = save_file(file)

        if unique_filename:
            user_id = current_user.id   #获取当前用户id
            new_file = File(
                user_id=user_id,
                file_path=file_path,
                file_name=unique_filename,
                original_file_name=original_filename
            )
            db.session.add(new_file)
            db.session.commit()
            flash('上传成功')
            return redirect(url_for('file.cleaned_display', file_id=new_file.id))
        else:
            flash('不支持的文件类型')
            return redirect(url_for('file.upload'))

    return render_template('upload.html', form=form)

@file_bp.route('/delete/<int:file_id>', methods=['GET', 'POST'])
@login_required
def delete(file_id):
    file = File.query.get_or_404(file_id)
    file_path = file.file_path
    # 删掉文件夹里的
    if os.path.exists(file_path):
        os.remove(file_path)
    db.session.delete(file)
    db.session.commit()
    flash('删除成功')
    return render_template('profile.html')

@file_bp.route('/cleaned_display/<int:file_id>')
def cleaned_display(file_id):
    file = File.query.get_or_404(file_id)
    # 读取数据
    raw_data = read_file(file.file_path)
    # 清洗
    cleaned_data = clean_data(raw_data)
    # 获得指标
    original_metrics = get_original_metrics(raw_data)
    cleaned_metrics = get_cleaned_metrics(cleaned_data)
    # 将清洗后的数据转换为HTML表格
    cleaned_data_html = cleaned_data.head(10).to_html(classes='table table-striped', index=False)
    return render_template('cleaned_display.html',
                           table=cleaned_data_html,
                           original_metrics=original_metrics,
                           cleaned_metrics=cleaned_metrics)

@file_bp.route('/analysis/<int:file_id>')
def analysis(file_id):
    file = File.query.get_or_404(file_id)
    raw_data = read_file(file.file_path)
    cleaned_data = clean_data(raw_data)
    descriptive_stats = get_descriptive_stats(cleaned_data)
    descriptive_stats = descriptive_stats.to_html(classes='table table-striped', index=False)
    return render_template('analysis.html', table=descriptive_stats)

app/blueprints/main.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.forms import DataAnalysisForm, PlotForm
from app.models import File, User
from flask_login import current_user
from .utils import read_file
from .utils_plot import plot_data
from .utils_analysis import clean_data, get_descriptive_stats
main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    return render_template('index.html')


@main_bp.route('/data_display')
def data_display():
    if current_user.is_authenticated:
        user = User.query.filter_by(username=current_user.username).first()
        uploaded_files = File.query.filter_by(user_id=user.id).all()
        print("Uploaded Files in index:", uploaded_files)  # 调试输出
    else:
        uploaded_files = File.query.all()
        flash('请登录')
    return render_template('data_analysis.html', uploaded_files=uploaded_files)


@main_bp.route('/data_analysis/<file_id>', methods=['GET', 'POST'])
def data_analysis(file_id):
    # 获取数据
    data_form = DataAnalysisForm()
    file = File.query.get_or_404(file_id)
    data = read_file(file.file_path)
    # 提取列名
    columns = data.columns.tolist()
    numeric_columns = data.select_dtypes(include='number').columns.tolist()

    # 填充data_form
    data_form.exclude_column.choices = [(col, col) for col in columns]
    data_form.unneccessary_column.choices = [(col, col) for col in columns]

    # 初始化描述性统计，以防不满足条件不存在
    descriptive_stats = None

    if data_form.validate_on_submit():
        # 数据预处理
        fillna_method = data_form.fillna_method.data
        exclude_columns =  data_form.exclude_column.data
        unneccessary_columns = data_form.unneccessary_column.data

        cleaned_data = clean_data(data,
                                  unneccessary_columns,
                                  exclude_columns,
                                  fillna_method)

        descriptive_stats = get_descriptive_stats(cleaned_data)
        descriptive_stats = descriptive_stats.to_html()

    return render_template('data_analysis_display.html',
                           data_form=data_form,
                           descriptive_stats=descriptive_stats,
                           file=file)

app/blueprints/plot.py
from flask import Blueprint, render_template
from app.models import *
from .utils import read_file
from .utils_analysis import clean_data, remove_outliers
from .utils_plot import *
from app.forms import PlotForm
import json
import plotly

plot_bp = Blueprint('plot', __name__)

@plot_bp.route('/plot/<int:file_id>', methods=['GET', 'POST'])
def plot(file_id):
    form = PlotForm()
    # 获取数据
    file = File.query.get_or_404(file_id)
    data = read_file(file.file_path)
    print(type(data))
    columns = data.columns.tolist()  # 提取列名
    numeric_columns = data.select_dtypes(include='number').columns.tolist() # 也可以include=['int', 'float']
    # 动态选择填充框的选项，没有这个只有画图函数的话里面的choices是空的
    # SelectField里面的choices属性对象可以是一个包含元祖的列表，这个元组由(显示值，提交值)组成
    # 显示值就是下拉菜单时显示给用户的内容，提交值就是用户提交表单时传递到后端的值。
    # 不是元祖的话就只能显示一样的
    # form.x_column.choices = [col for col in cleaned_data.columns]   # index对象不行，要是list，也可 cleaned_data.columns.tolist()
    # form.y_column.choices = [(col, col) for col in cleaned_data.columns]


    # 填充选择框
    form.x_column.choices = [(col, col) for col in columns]
    form.y_columns.choices = [(col, col) for col in columns]
    # 当用户选择“无”时，color_column 和 size_column 的值会为 ''。在代码中，这两个字段会被转换为 None，以避免数据绘制时的 KeyError
    form.color_column.choices = [('', '无')] + [(col, col) for col in columns]
    form.size_column.choices = [('', '无')] + [(col, col) for col in numeric_columns]
    form.sort_column.choices = [(col, col) for col in numeric_columns]
    print(form.sort_column.choices)
    form.exclude_column.choices = [(col, col) for col in columns]
    form.unneccessary_column.choices = [(col, col) for col in columns]
    # 初始化fig
    fig = None

    if form.validate_on_submit():
        print("表单验证通过")
        print("表单数据:", form.data)  # 输出所有表单数据

        # 获取表单输入的
        # 数据预处理
        fillna_method = form.fillna_method.data
        print(fillna_method)
        unneccessary_columns = form.unneccessary_column.data
        excluded_columns = form.exclude_column.data
        cleaned_data = clean_data(data, unneccessary_columns, excluded_columns, fillna_method)
        # 启用移动平均
        use_moving_average = form.use_moving_average.data
        moving_average_window = form.moving_average_window.data
        # 其他
        chart_type = form.chart_type.data
        num_rows = form.num_rows.data
        # 根据图表所需选择字段
        x_column = form.x_column.data
        y_columns = form.y_columns.data
        # 在视图函数中，我们用 .data or None 的方式确保如果用户选择了“无”，下拉框字段的值会为 None，而不是空字符串。这样做可以避免 plot_data() 函数试图查找不存在的列时抛出 KeyError 错误。
        color_column = form.color_column.data or None
        size_column = form.size_column.data or None
        sort_column = form.sort_column.data
        sort_order = form.sort_order.data

        # # 清理异常值
        # excluded_columns = form.exclude_column.data
        # included_columns = []
        # for col in numeric_columns:
        #     if col not in excluded_columns:
        #         included_columns.append(col)
        # if included_columns:
        #     cleaned_data = clean_data(cleaned_data, included_columns)

        # 排序,这里排完顺序再绘图，不用传参数给绘图函数
        selected_data = cleaned_data.head(num_rows)
        ascending = (sort_order == 'asc')
        selected_data = selected_data.sort_values(by=sort_column, ascending=ascending)  #是asc的话就返回true
        # 绘图
        fig, fig_json = plot_data(
            selected_data,
            x_column,
            y_columns,
            chart_type,
            color_column,
            size_column,
            use_moving_average,
            moving_average_window or 5
        )
        if fig is None:
            print("Error: plot_data did not return a figure.")
        if fig_json is None:
            print("Error: plot_data did not return a figure.")
        return render_template('plot.html', fig=fig, form=form, fig_json=fig_json)  # 将图形传递给模板
    else:
        print(form.errors)
    return render_template('plot.html', form=form)

app/templates/analysis.html
{% extends 'base.html' %}


{% block title %}分析结果{% endblock %}

{% block content %}
<div>
    <h1>描述性统计数据</h1>
    <div>
        <ul>
            <li>1.均值：反映数据集的中心位置，是所有观测值的算术平均。这个统计量能够帮助您理解数据的整体水平。</li>
            <li>2.标准差：度量数据的离散程度，标准差越大表示数据的波动越大。通过标准差，您可以评估数据的波动性。</li>
            <li>3.中位数：将数据集按升序排列后，位于中间的值。中位数可以有效抵御极端值的影响，提供更稳健的中心位置度量。</li>
            <li>4.最小值：数据集中最小的观测值。最小值有助于了解数据的下限。</li>
            <li>5.最大值：数据集中最大的观测值。最大值可以显示数据的上限，帮助识别潜在的异常值。</li>
            <li>6.偏度：描述数据分布的对称性。偏度为正表示数据右偏，偏度为负则表示左偏。偏度的值接近零则说明数据分布较为对称。</li>
            <li>7.峰度：描述数据分布的陡峭程度。峰度值高说明数据分布集中在均值附近，峰度值低则表示数据较为分散。</li>
        </ul>
    </div>
    <h2>结果如下:</h2>
    <div>
        {{ table | safe }}
    </div>
</div>


{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}数据分析{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
<body>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div>{{ message }}</div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <header>
        <nav>
            <ul>
                <li><a href="/">首页</a></li>
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('auth.profile') }}">个人中心</a></li>
                    <li><a href="{{ url_for('main.data_display') }}">数据分析</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">登出</a></li>
                {% else %}
                    <li><a href="{{ url_for('auth.login') }}">登录</a></li>
                    <li><a href="{{ url_for('auth.register') }}">注册</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <div>
        {% block content %}
        <!-- 页面内容将在这里插入 -->
        {% endblock %}
    </div>

    <footer>
        <span>© 2024 zmq_data</span>
    </footer>
</body>


</html>

app/templates/cleaned_display.html
{% extends 'base.html' %}

{% block title %}清洗结果{% endblock %}

{% block content %}
    <div>
        <table border="1">
            <h1>原数据集</h1>
            <tr>
                <th>指标</th>
                <th>值</th>
            </tr>
            {% for metric, value in original_metrics.items() %}
            <tr>
                <td>{{ metric }}</td>
                <td>{{ value }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <div>
        <table border="1">
            <h1>清洗后数据集</h1>
            <tr>
                <th>指标</th>
                <th>值</th>
            </tr>
            {% for metric, value in cleaned_metrics.items() %}
            <tr>
                <td>{{ metric }}</td>
                <td>{{ value }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div>
        <h2>前10行</h2>
        {{ table | safe }}
    </div>
{% endblock %}

app/templates/data_analysis.html
{% extends 'base.html' %}

{% block content %}
    <ul>
        {% if uploaded_files %}
            {% for file in uploaded_files %}
                <li>
                    <a href="{{ url_for('main.data_analysis', file_id=file.id) }}">{{ file.original_file_name }}</a>
                </li>
            {% endfor %}
        {% else %}
            <li>没有找到上传的文件。</li>
        {% endif %}
    </ul>

{% endblock %}

app/templates/data_analysis_display.html
{% extends 'base.html' %}

{% block content %}
    <h1>数据分析</h1>

    <form method="post">
        {{ data_form.hidden_tag() }}
        <div>
            {{ data_form.fillna_method.label }} {{ data_form.fillna_method() }}
        </div>
        <div>
            {{ data_form.exclude_column.label }} {{ data_form.exclude_column(class='form-control select2') }}
        </div>
        <br>
        <div>
            {{ data_form.unneccessary_column.label }} {{ data_form.unneccessary_column() }}
        </div>
        <br>
        <div>{{ data_form.submit() }}</div>
    </form>

    {% if descriptive_stats %}
        <h2>描述性统计</h2>
        <pre>{{ descriptive_stats|safe }}</pre>
    {% endif %}

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %}首页{% endblock %}
{% block content %}
    <div>
        <a href="{{ url_for('file.upload') }}">上传文件</a>
    </div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}


{% block title %}登录{% endblock %}
{% block content %}
    <form action="{{ url_for('auth.login') }}" method="post">
        {{ form.hidden_tag() }}
        {{ form.username.label }} {{ form.username() }} <br>
        {{ form.password.label }} {{ form.password() }} <br>
        {{ form.submit() }}
    </form>
{% endblock %}

app/templates/plot.html
{% extends 'base.html' %}

{% block title %}图像{% endblock %}
{% block content %}
    <form method="POST">
    {{ form.hidden_tag() }}

    <div title="选择是否启用移动平均">
        {{ form.use_moving_average.label }}
        {{ form.use_moving_average }}
    </div>
    <div title="选择几个数据点位一组">
        {{ form.moving_average_window.label }}
        {{ form.moving_average_window }}
    </div>
    <div title="选择作为X轴的字段">
        {{ form.x_column.label }}<br>
        {{ form.x_column() }}
    </div>

    <div title="选择作为Y轴的字段">
        {{ form.y_columns.label }} <small>(折线图可选多个y轴)</small> <br>
        {{ form.y_columns() }}
    </div>

    <div title="选择用于调整图表中数据点大小的字段。字段必须为数值类型。">
    {{ form.size_column.label }}
    {{ form.size_column() }}
    </div>

    <div title="选择用于排序图表数据的字段。">
        {{ form.sort_column.label }}
        {{ form.sort_column() }}
    </div>

    <div title="选择数据排序的顺序：升序或降序。">
        {{ form.sort_order.label }}
        {{ form.sort_order }}
    </div>

    <div title="选择用于图表颜色分组的字段（可选）。可以选择任何字段作为颜色分组依据。">
        {{ form.color_column.label }}
        {{ form.color_column() }}
    </div>

    <div title="选择显示的行数">
        {{ form.num_rows.label }}
        {{ form.num_rows }}
    </div>

    <div title="选择图表类型。">
        {{ form.chart_type.label }}
        {{ form.chart_type() }}
    </div>

    <div title="选择不用清理异常值的列" style="max-height: 200px; overflow-y: auto;">
        {{ form.exclude_column.label }}
        <br>
        {{ form.exclude_column() }}
    </div>

    <div title="选择不需要的列" style="max-height: 200px; overflow-y: auto;">
        {{ form.unneccessary_column.label }}<br>
        {{ form.unneccessary_column() }}
    </div>

    <div title="选择填充缺失值方式">
        {{ form.fillna_method.label }}
        {{ form.fillna_method() }}
    </div>

    {{ form.submit() }}
    </form>

    <div id="plotly-div" style="width:100%;height:500px;"></div>
    <script>
        function renderPlotly(figJson) {
            // 解析Python传来的JSON数据,将flask传来的json字符串转换为JavaScript对象
            const plotData = JSON.parse(figJson);
            // 使用解析后的数据和布局渲染图表
            Plotly.newPlot('plotly-div', plotData.data, plotData.layout);
        }

        const pythonFigJson = '{{ fig_json | safe }}';  // 这里使用模板引擎变量
        if (pythonFigJson) {
            renderPlotly(pythonFigJson);
        }
    </script>
{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}

{% block title %}个人中心{% endblock %}
{% block content %}
    <h1>个人中心</h1>
    {% if current_user.is_authenticated %}
            {% for file in uploaded_files %}
                <h1>{{ file.original_file_name }}</h1>
                <ul class="ula">
                    <li><a href="{{ url_for('file.cleaned_display', file_id=file.id) }}">预处理</a></li>
                    <li><a href="{{ url_for('file.analysis', file_id=file.id) }}">分析</a></li>
                    <li><a href="{{ url_for('plot.plot', file_id=file.id) }}">画图</a></li>
                    <li><a href="{{ url_for('file.delete', file_id=file.id) }}">删除</a></li>
                </ul>
            {% endfor %}
    {% endif %}
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block title %}注册{% endblock %}
{% block content %}
    <form action="{{ url_for('auth.register') }}" method="post">
        {{ form.hidden_tag() }}
        {{ form.username.label }} {{ form.username }} <br>
        {{ form.email.label }}  {{ form.email }} <br>
        {{ form.password.label }}  {{ form.password }} <br>
        {{ form.confirm_password.label }}  {{ form.confirm_password }} <br>
        {{ form.submit }}
    </form>
{% endblock %}

app/templates/upload.html
{% extends 'base.html' %}
{% block title %}文件上传{% endblock %}
{% block content %}
    <form action="{{ url_for('file.upload') }}" method="post" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        {{ form.file.label }} {{ form.file }} <br>
        {{ form.submit }}
    </form>
{% endblock %}